# Generated by Django 4.2.5 on 2025-11-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFCodexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('page_number', models.IntegerField()),
                ('cleaned_text', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('embedding', models.JSONField()),
                ('source', models.CharField(default='pdf', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
