# Generated by Django 4.2.5 on 2025-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baybayin_codex_pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ai_analysis_reasoning',
            field=models.TextField(blank=True, help_text='AI explanation of difficulty rating', null=True),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='When AI last analyzed this content', null=True),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ai_category',
            field=models.CharField(blank=True, help_text='AI-determined learning category', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ai_cognitive_level',
            field=models.CharField(blank=True, help_text='AI-determined cognitive complexity', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ai_difficulty_score',
            field=models.FloatField(blank=True, help_text='AI-calculated difficulty (0=easiest, 1=hardest)', null=True),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ai_estimated_minutes',
            field=models.IntegerField(blank=True, help_text='AI-estimated study time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ai_prerequisites',
            field=models.JSONField(blank=True, default=list, help_text='AI-identified prerequisite concepts'),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='average_response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='times_answered_correctly',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='times_asked',
            field=models.IntegerField(default=0),
        ),
    ]
