# Generated by Django 4.2.5 on 2025-12-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baybayin_codex_pdf', '0002_pdfcodexentry_ai_analysis_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ocr_confidence_score',
            field=models.FloatField(blank=True, help_text='OCR text quality confidence score (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ocr_config_used',
            field=models.CharField(blank=True, help_text='Tesseract configuration that produced the best result', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pdfcodexentry',
            name='ocr_sanitization_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Statistics from OCR text sanitization process'),
        ),
    ]
