# Generated by Django 5.2.4 on 2025-07-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baybayin_wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikiglossary',
            name='baybayin_script',
        ),
        migrations.RemoveField(
            model_name='wikiglossary',
            name='pronunciation',
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='source',
            field=models.CharField(default='manual', help_text='Source of the content (wikipedia, ncca, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original URL of the content'),
        ),
        migrations.AddField(
            model_name='wikiglossary',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='wikiglossary',
            name='source',
            field=models.CharField(blank=True, help_text='Source of the glossary term', max_length=200),
        ),
        migrations.AddField(
            model_name='wikiglossary',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original URL of the glossary term'),
        ),
        migrations.AddField(
            model_name='wikitimeline',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original URL of the timeline information'),
        ),
    ]
