# Generated by Django 5.2.4 on 2025-07-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baybayin_wiki', '0002_remove_wikiglossary_baybayin_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikicategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wikiglossary',
            name='baybayin_script',
            field=models.CharField(blank=True, help_text='Baybayin representation', max_length=100),
        ),
        migrations.AddField(
            model_name='wikiglossary',
            name='etymology',
            field=models.TextField(blank=True, help_text='Word origin and etymology'),
        ),
        migrations.AddField(
            model_name='wikiglossary',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata from scraping'),
        ),
        migrations.AddField(
            model_name='wikiglossary',
            name='pronunciation',
            field=models.CharField(blank=True, help_text='Pronunciation guide', max_length=100),
        ),
        migrations.AddField(
            model_name='wikiglossary',
            name='usage_examples',
            field=models.JSONField(blank=True, default=list, help_text='Usage examples'),
        ),
        migrations.AddField(
            model_name='wikitimeline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata from scraping'),
        ),
    ]
