# Generated by Django 5.2.4 on 2025-07-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baybayin_wiki', '0003_wikicategory_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiarticle',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty field for scraper compatibility', max_length=20),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata from scraping'),
        ),
        migrations.AddField(
            model_name='wikiarticle',
            name='url',
            field=models.URLField(blank=True, help_text='URL field for scraper compatibility'),
        ),
        migrations.AddField(
            model_name='wikicategory',
            name='article_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wikitimeline',
            name='date',
            field=models.CharField(blank=True, help_text='Date field for scraper compatibility', max_length=100),
        ),
    ]
