# Generated by Django 5.2.4 on 2025-07-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baybayin_wiki', '0004_wikiarticle_difficulty_wikiarticle_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wikiarticle',
            name='baybayin_wi_categor_140041_idx',
        ),
        migrations.RemoveIndex(
            model_name='wikiarticle',
            name='baybayin_wi_is_feat_517f35_idx',
        ),
        migrations.AddField(
            model_name='wikitimeline',
            name='importance_level',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='wikitimeline',
            name='related_articles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='wikitimeline',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='baybayin_examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='featured_image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='interactive_elements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='source',
            field=models.CharField(default='manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='wikiarticle',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wikiglossary',
            name='baybayin_script',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wikiglossary',
            name='etymology',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wikiglossary',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wikiglossary',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wikiglossary',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wikiglossary',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='wikiglossary',
            name='usage_examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='wikitimeline',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wikitimeline',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='wikitimeline',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
