# Generated by Django 5.2.4 on 2025-07-18 16:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_seg_trivia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='triviaquestionhistory',
            old_name='question',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='triviaquestionhistory',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation or hint for incorrect answers', null=True),
        ),
        migrations.AddField(
            model_name='triviaquestionhistory',
            name='source_fact',
            field=models.JSONField(blank=True, help_text='ID and type of source fact(s) used', null=True),
        ),
        migrations.AddField(
            model_name='usertriviaprofile',
            name='consecutive_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertriviaprofile',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usertriviaprofile',
            name='current_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertriviaprofile',
            name='mastery_level',
            field=models.IntegerField(default=1, help_text="User's Baybayin mastery level (1-10)"),
        ),
        migrations.AddField(
            model_name='usertriviaprofile',
            name='moves_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertriviaprofile',
            name='session_moves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertriviaprofile',
            name='session_start',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertriviaprofile',
            name='top_weaknesses',
            field=models.JSONField(default=list, help_text='Top 3 weak areas'),
        ),
        migrations.AddField(
            model_name='usertriviaprofile',
            name='weaknesses',
            field=models.JSONField(default=dict, help_text='Dictionary of topics with error counts'),
        ),
        migrations.AlterField(
            model_name='triviaquestionhistory',
            name='correct_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='triviaquestionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triviaquestionhistory',
            name='user_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usertriviaprofile',
            name='total_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertriviaprofile',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertriviaprofile',
            name='total_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertriviaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
