# Generated by Django 5.2.4 on 2025-07-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_seg_trivia', '0002_rename_question_triviaquestionhistory_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triviaquestionhistory',
            name='explanation',
        ),
        migrations.AddField(
            model_name='triviaquestionhistory',
            name='question_type',
            field=models.CharField(choices=[('basic_fact', 'Basic Fact'), ('historical_context', 'Historical Context'), ('linguistic_analysis', 'Linguistic Analysis'), ('comparative_analysis', 'Comparative Analysis')], default='basic_fact', max_length=50),
        ),
    ]
