# Generated by Django 5.2.4 on 2025-10-05 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_seg_trivia', '0003_remove_triviaquestionhistory_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('wiki', 'Wiki'), ('manual', 'Manual Entry')], default='book', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debug_file_path', models.TextField(blank=True, help_text='Path to debug file for OCR verification', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriviaSourceFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The actual text content of this chunk')),
                ('embedding', models.JSONField(help_text='Vector embedding of the content (list of floats)')),
                ('token_count', models.IntegerField(help_text='Approximate number of tokens in content')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata like page number, chapter, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='game_seg_trivia.triviaarchive')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_archive'], name='game_seg_tr_source__93093d_idx'), models.Index(fields=['token_count'], name='game_seg_tr_token_c_77370e_idx')],
            },
        ),
    ]
