# Generated by Django 5.2.4 on 2025-11-04 12:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_seg_trivia', '0004_triviaarchive_triviasourcefact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triviaquestionhistory',
            options={'ordering': ['-answered_at'], 'verbose_name_plural': 'Trivia question histories'},
        ),
        migrations.RenameField(
            model_name='triviaquestionhistory',
            old_name='timestamp',
            new_name='answered_at',
        ),
        migrations.RemoveField(
            model_name='triviaquestionhistory',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='triviaquestionhistory',
            name='options',
        ),
        migrations.RemoveField(
            model_name='triviaquestionhistory',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='triviaquestionhistory',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='triviaquestionhistory',
            name='source_fact',
        ),
        migrations.AddField(
            model_name='triviaquestionhistory',
            name='session_id',
            field=models.CharField(blank=True, help_text='Game session identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='triviaquestionhistory',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Time taken to answer in seconds', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='triviaarchive',
            name='source_type',
            field=models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('codex', 'Codex'), ('manual', 'Manual Entry')], default='book', max_length=50),
        ),
        migrations.AlterField(
            model_name='triviaquestionhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='triviaquestionhistory',
            name='user_answer',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='TriviaQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The trivia question text')),
                ('correct_answer', models.CharField(help_text='The correct answer', max_length=500)),
                ('options', models.JSONField(help_text='List of answer options')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('source', models.TextField(blank=True, help_text='Source reference')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Question tags/categories')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('times_used', models.IntegerField(default=0, help_text='How many times this question was used')),
                ('times_correct', models.IntegerField(default=0, help_text='How many times answered correctly')),
                ('times_incorrect', models.IntegerField(default=0, help_text='How many times answered incorrectly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('basic_fact', 'Basic Fact'), ('historical_context', 'Historical Context'), ('linguistic_analysis', 'Linguistic Analysis'), ('comparative_analysis', 'Comparative Analysis')], default='basic_fact', help_text='Category of question for adaptive learning', max_length=50)),
                ('source_facts', models.JSONField(blank=True, default=list, help_text='IDs of TriviaSourceFact records used to generate this question')),
                ('archive_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='game_seg_trivia.triviaarchive')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='triviaquestionhistory',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='game_seg_trivia.triviaquestion'),
        ),
        migrations.AddIndex(
            model_name='triviaquestionhistory',
            index=models.Index(fields=['user', 'answered_at'], name='game_seg_tr_user_id_5d10b5_idx'),
        ),
        migrations.AddIndex(
            model_name='triviaquestionhistory',
            index=models.Index(fields=['session_id'], name='game_seg_tr_session_361dae_idx'),
        ),
        migrations.AddIndex(
            model_name='triviaquestionhistory',
            index=models.Index(fields=['is_correct'], name='game_seg_tr_is_corr_b8faf1_idx'),
        ),
        migrations.AddIndex(
            model_name='triviaquestion',
            index=models.Index(fields=['difficulty'], name='game_seg_tr_difficu_87d09e_idx'),
        ),
        migrations.AddIndex(
            model_name='triviaquestion',
            index=models.Index(fields=['created_at'], name='game_seg_tr_created_82d39e_idx'),
        ),
        migrations.AddIndex(
            model_name='triviaquestion',
            index=models.Index(fields=['times_used'], name='game_seg_tr_times_u_9aeb06_idx'),
        ),
    ]
