# Generated by Django 5.2.4 on 2025-01-XX XX:XX

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baybayin_codex', '0001_initial'),
        ('game_seg_trivia', '0005_alter_triviaquestionhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='source_article',
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the originating Codex article for 'Learn More' feature",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trivia_questions',
                to='baybayin_codex.codexarticle'
            ),
        ),
        migrations.AddIndex(
            model_name='triviaquestion',
            index=models.Index(fields=['source_article'], name='game_seg_tr_source__idx'),
        ),
    ]
