# Generated by Django 4.2.5 on 2025-11-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_seg_trivia', '0006_triviaquestion_source_article'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='triviaquestion',
            new_name='game_seg_tr_source__133a00_idx',
            old_name='game_seg_tr_source__idx',
        ),
    ]
