# Generated by Django 4.2.5 on 2025-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_seg_trivia', '0007_rename_game_seg_tr_source__idx_game_seg_tr_source__133a00_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviasourcefact',
            name='embedding_json',
            field=models.TextField(default='[]', help_text='Vector embedding as JSON-serialized array of floats (thesis requirement)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triviasourcefact',
            name='embedding',
            field=models.JSONField(blank=True, help_text='DEPRECATED: Use embedding_json instead', null=True),
        ),
    ]
