# Generated by Django 4.2.5 on 2025-11-17 08:05

from django.db import migrations


def populate_source_fact_from_legacy(apps, schema_editor):
    """
    Migrate data from source_facts JSONField to source_fact ForeignKey
    This ensures Golden Thread traceability per thesis requirements
    """
    TriviaQuestion = apps.get_model('game_seg_trivia', 'TriviaQuestion')
    TriviaSourceFact = apps.get_model('game_seg_trivia', 'TriviaSourceFact')
    
    updated_count = 0
    for question in TriviaQuestion.objects.all():
        # Skip if source_fact already set
        if question.source_fact_id:
            continue
        
        # Check if legacy source_facts has data
        if question.source_facts and len(question.source_facts) > 0:
            first_fact_id = question.source_facts[0]
            
            # Try to find the TriviaSourceFact by ID
            try:
                fact = TriviaSourceFact.objects.get(id=first_fact_id)
                question.source_fact = fact
                question.save(update_fields=['source_fact'])
                updated_count += 1
            except TriviaSourceFact.DoesNotExist:
                # Fact doesn't exist, skip
                pass
    
    print(f"Migrated {updated_count} questions to use source_fact FK")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - not needed as we're keeping both fields
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('game_seg_trivia', '0008_triviasourcefact_embedding_json_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_source_fact_from_legacy, reverse_migration),
    ]
