# Generated by Django 4.2.5 on 2025-12-14 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import game_seg_trivia.models


class Migration(migrations.Migration):

    dependencies = [
        ('baybayin_codex_pdf', '0002_pdfcodexentry_ai_analysis_reasoning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_seg_trivia', '0009_populate_source_fact_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='triviaquestion',
            name='source_fact',
            field=models.ForeignKey(blank=True, help_text='PRIMARY source fact used to generate this question (thesis traceability requirement)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_questions', to='game_seg_trivia.triviasourcefact'),
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_skill', models.FloatField(default=1000.0, help_text='Elo-style skill rating (800=novice, 1000=average, 1200+=advanced)')),
                ('category_skills', models.JSONField(default=dict, help_text="AI-tracked skill per category: {'character_basics': 950, 'vowel_system': 1020, ...}")),
                ('learning_rate', models.FloatField(default=1.0, help_text='AI-calculated learning speed multiplier (1.0 = normal, >1 = fast learner)')),
                ('skill_uncertainty', models.FloatField(default=350.0, help_text="AI's confidence in skill estimate (decreases with more questions answered)")),
                ('optimal_difficulty_range', models.JSONField(default=game_seg_trivia.models.default_difficulty_range, help_text='AI-calculated optimal challenge zone for this user')),
                ('recent_performance', models.JSONField(default=list, help_text='Last 50 question results for AI analysis and pattern detection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Skill Profile (AI-Adaptive)',
                'verbose_name_plural': 'User Skill Profiles (AI-Adaptive)',
            },
        ),
        migrations.CreateModel(
            name='TriviaQuestionAnswered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField()),
                ('response_time_seconds', models.FloatField(help_text='Time taken to answer in seconds')),
                ('question_difficulty', models.FloatField(blank=True, help_text='Difficulty of question at time of answering', null=True)),
                ('user_skill_at_time', models.FloatField(blank=True, help_text="User's skill level when they answered", null=True)),
                ('skill_change', models.FloatField(blank=True, help_text='How much skill changed from this answer', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='game_seg_trivia.triviaquestion')),
                ('source_fact', models.ForeignKey(blank=True, help_text='PDF source for this question', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baybayin_codex_pdf.pdfcodexentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trivia Question Answered',
                'verbose_name_plural': 'Trivia Questions Answered',
                'ordering': ['-answered_at'],
                'indexes': [models.Index(fields=['user', 'answered_at'], name='game_seg_tr_user_id_32b702_idx'), models.Index(fields=['is_correct'], name='game_seg_tr_is_corr_83a983_idx'), models.Index(fields=['source_fact'], name='game_seg_tr_source__cdf302_idx')],
            },
        ),
    ]
