# Generated by Django 5.2.4 on 2025-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_transliteration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, unique=True)),
                (
                    "params",
                    models.JSONField(
                        help_text="Define parameter names and expected data types as JSON"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelPipelineMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("preprocessing", "Preprocessing"),
                            ("feature_extraction", "Feature Extraction"),
                            ("feature_encoding", "Feature Encoding"),
                            ("classification", "Classification"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ClassificationModelMethod",
        ),
        migrations.DeleteModel(
            name="FeatureExtractionMethod",
        ),
        migrations.DeleteModel(
            name="PreprocessingMethod",
        ),
        migrations.DeleteModel(
            name="VocabularyBuildingMethod",
        ),
    ]
