# Generated by Django 5.2.4 on 2025-10-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_transliteration", "0002_modelconfig_modelpipelinemethod_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="complete_name",
            field=models.CharField(
                default="",
                help_text="Full descriptive name of the model",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="modelpipelinemethod",
            name="complete_name",
            field=models.CharField(
                default="",
                help_text="Full descriptive name of the method",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
