# Generated by Django 5.2.4 on 2025-10-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_transliteration", "0003_modelconfig_complete_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelconfig",
            name="category",
            field=models.CharField(
                choices=[
                    ("feature_extraction", "Feature Extraction"),
                    ("feature_encoding", "Feature Encoding"),
                    ("classification", "Classification"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
